REM Copyright (c) 2016-2021 James Cook
set eudir=%ONEDRIVE%\euphoria40
set path=%eudir%\bin;%path%
echo Open Watcom Build Environment
SET PATH=%ONEDRIVE%\EUPHORIA\WATCOM\BINW;%PATH%
SET PATH=%ONEDRIVE%\EUPHORIA\WATCOM\BINNT;%PATH%
SET INCLUDE=%ONEDRIVE%\EUPHORIA\WATCOM\H\NT;%INCLUDE%
SET INCLUDE=%ONEDRIVE%\EUPHORIA\WATCOM\H\NT;%INCLUDE%
SET INCLUDE=%INCLUDE%;%ONEDRIVE%\EUPHORIA\WATCOM\H\NT\DIRECTX
SET INCLUDE=%INCLUDE%;%ONEDRIVE%\EUPHORIA\WATCOM\H\NT\DDK
SET INCLUDE=%ONEDRIVE%\EUPHORIA\WATCOM\H;%INCLUDE%
SET WATCOM=%ONEDRIVE%\EUPHORIA\WATCOM
SET EDPATH=%ONEDRIVE%\EUPHORIA\WATCOM\EDDAT
SET WHTMLHELP=%ONEDRIVE%\EUPHORIA\WATCOM\BINNT\HELP
SET WIPFC=%ONEDRIVE%\EUPHORIA\WATCOM\WIPFC
pause
euc -o libminieun.dll -strict -dll -wat -keep libminieun.e
upx libminieun.dll
pause
euc -o libmyeun.dll -strict -dll -wat -keep libeun.e
upx libmyeun.dll
pause
cl386.exe TestLibMyEun.c
upx TestLibMyEun.exe
pause
TestLibMyEun
pause
